<?php
	$title = "Podcast: What's Next? How Mobile is Changing Design";
	$section = "podcast";
?>

<?php $dr = str_replace($_SERVER['SCRIPT_NAME'], '/includes/', $_SERVER['SCRIPT_FILENAME']); ?>

<?php include($dr . "head.inc.php"); ?><!-- HEADER -->

<!-- SECTION PODCAST -->
<div class="section">

<h1>What's Next? How Mobile is Changing Design</h1>
<h2 class="vcard"><a href="/schedule/brianfling" class="fn url">Brian Fling</a></h2>

<p><a href="http://dconstruct.s3.amazonaws.com/2009/podcast/dConstruct2009-Fling.mp3" rel="enclosure" type="audio/mpeg">Download the audio</a></p>
<object type="application/x-shockwave-flash" data="http://huffduffer.com/flash/player.swf?soundFile=http://dconstruct.s3.amazonaws.com/2009/podcast/dConstruct2009-Fling.mp3" width="290" height="24"><param name="movie" value="http://huffduffer.com/flash/player.swf?soundFile=http://dconstruct.s3.amazonaws.com/2009/podcast/dConstruct2009-Fling.mp3"><param name="wmode" value="transparent"><a href="http://huffduffer.com/dConstruct/7908">What’s Next? How Mobile is Changing Design by Brian Fling on Huffduffer</a></object>
<p><a href="http://huffduffer.com/add/7908">Huffduff it</a>

<p>Podcast transcripts brought to you by the <a href="http://www.opera.com/developer">Opera Developer Network</a></p>

<cite>Brian</cite>:

<blockquote>
<p>So this is one of my favourite topics, what&#8217;s next? It&#8217;s great because I&#8217;m not really held accountable for anything so I can be completely wrong about everything I say. And it&#8217;s also kind of fun because this is one of the rare opportunities I get to bring you into my head &mdash;so it moves a little fast, so hopefully, everyone will keep up.</p>

<p>So basically, I was born in 1975, March 17th to be precise, and back then this was the fashion of the day, and when we talked about tomorrow, this was kind of our frame of reference. And Nathan and Chris are actually going to be talking about this after lunch, but I think it&#8217;s really interesting the perspective that we have about what comes tomorrow and what the future is going to hold. And thinking about, like, all these miraculous inventions of the future, and this perspective in this&hellip; I mean I actually remember, I was digging up some of these photos, I remember seeing many of these in the library when I was growing up and this was my perspective of what the future is going to be, and of course, you know, this was a little bit before my time but it was right around the time when I was growing up &mdash;this show was definitely in syndication &mdash;and then&hellip; and also I think it&#8217;s also interesting, the predictions of the future that we have like, for example, this is what Michael Jackson was supposed to look like in the year 2000. </p>

<p>But one of the things that happened in the early Seventies actually, was this thing called Nixon shock, which was basically&hellip; or it&#8217;s often referred to as the death of money&hellip; which was the change of our monetary system. And one of the things that kind of occurred there was the gas crisis that happened right about the same time that I was born. In fact my Mum tells me that I was&hellip; you know, this is back before the days of seat-belts, I used to be in the back of the car while she would wait in lines. But it&#8217;s interesting when we look at what happened is we have&hellip; the most recent gas crisis that we had just in 2006, was very similar to the one that we had back in the Seventies and this was because of this monetisation change. And I also think it&#8217;s interesting that, you know, we used to have the conception, when I was born, this conception of computers kind of changed, that actually in the same year that I was born we went from computers that fit in rooms to these computers that you could kind of hack on and do things with on your desktop. And also, in 1975, this company was founded in BelleVue, Washington, not too far from where I live. </p>

<p>But the thing that is so fascinating about the future and tomorrow is flying cars, right? We always have this perception in the future we&#8217;re going to have flying cars, and I mean, this was my Saturday morning staple, seeing the old shows of the Jetsons one night and always thinking that in the future, in the year 2000 which was so far away, that there&#8217;d be these flying cars. So anyway, so we grew up in the Eighties &mdash;or I grew up in the Eighties and I think a lot of you are also did &mdash;so you probably actually remember some of these visuals again, kind of defining what the future is. That we were going to be exploring space and we were going to be wielding light sabres and that we would maybe be frozen in time and have little robots that made funny noises, and there&#8217;d be these alien cultures, and where be like, robots, lots and lots of robots. And I hope some people recognise this reference, one of my favourite shows growing up, and then something that&#8217;s probably a little bit more culturally relevant, this is actually something I did grow up with in the States, was this was my favourite doctor &mdash;this was the one&hellip; this was my first introduction to the doctor &mdash;something that we didn&#8217;t quite get in the States but you probably are familiar with, again, you know, you kind of define our perception of what tomorrow&#8217;s going to bring.</p>

<p>And then towards 1982 or so, it started getting a little bit darker, but still it didn&#8217;t really change our perception that we were still going to have flying cars, right? So we were like ok, it&#8217;s the Eighties, we&#8217;re going to have flying cars. So I think what was really interesting is, in 1984&hellip; so I would&#8217;ve been nine years old&hellip; in 1984&hellip; and I was suddenly faced with my own mortality, right? Because this was the height of the Cold War and the nuclear arms race, and so in the States, I hope you had it here, there&#8217;s a show called &#8216;The Day After&#8217; and it talked about the Apocalypse and there was this big thing that happened late in 1984, but this all happened at the height of the Cold War and I actually grew up in the mid-Eighties not actually thinking that I would live to see the year 2000 &mdash;as a nine year old! And so suddenly I felt like I was growing up and my future was starting to be taken away from me. And so all&hellip; this was just the news of the day, when I kind of reached an age where I could kind of understand some of the things that were going on. And this was&hellip; you can see, 1984/1985 is the height of the arms race. And in fact the Doomsday Clock &mdash;I&#8217;m sure there&#8217;s many Watchmen fans here &mdash;but the Doomsday Clock is a real thing and in 1984/1985, it was moved to three minutes to midnight, which is the closest it&#8217;s actually been to midnight since the Cuban missile crisis of the early Sixties.</p>

<p>So &mdash;now, what&#8217;s also interesting is looking at the thought of the day. In 1985 there was a survey that was done that most people said that they had at least three close friends they could talk to about and this is really interesting, I think, because it goes back to Abraham Maslow who talks about the hierarchy of needs, which basically says that in order for us to attain self actualisation, in order for us to do incredible things, we have to have some of our basic needs met. We have to feel safe and secure, and I think that&#8217;s interesting because my generation, I felt, was this&hellip; which is this Generation X, I was kind of the later in this Generation X &mdash;it was kind of the doomed generation, right? We didn&#8217;t really have much of a future, there was&hellip; right in front of us.. and so, I keep kind of thinking back is did that&hellip;. what was going on in 1984/1985, politically did that affect my perception of what tomorrow&#8217;s going to be? And I know myself very well that I&#8217;m this eternal optimist, and is it because I&#8217;m just thankful that I&#8217;m here today? You know, that I&#8217;ve gotten to this point. And so it&#8217;s also kind of interesting, 1984, that this little gadget came out which kind of redefined what computers could be for us, but still no flying cars.</p>

<p>Now the next year which I think is interesting is 1991. Now I was right about&hellip; I just about ready to graduate High School&hellip; but I think there was a very interesting cultural event that occurred in 1991 which, of course, was the fall of Communism, the fall of the Berlin Wall and after that we had all this economic prosperity and lots of different innovations that were kind of occurring, and I look at 1991 as being a real particular year because the eighteen year olds, nineteen year olds of today never knew the world that I knew. They grew after Communism, after the Cold War, and they grew up in this era of economic prosperity. And so it&#8217;s interesting how that affects their needs, that their needs kind of change where they don&#8217;t actually have the physiological and the safety concerns that other people in the world actually have today. But they didn&#8217;t really have those, in today, so that actually makes it a little bit easier for them to transcend up through Maslow&#8217;s hierarchy of needs.</p>

<p>So let&#8217;s fast forward a little bit to 1998. So the Internet thing kind of occurred and so we had &mdash;I got one of these a day in the mail, right? &mdash;and so, you know, we were&hellip; we started with the Internet kind of looking like this but in 1998, the Internet started to look like this, right? So it started to change a little bit, and so at this time, those people that were born in 1991, this Generation Y, they started to recognise computers as looking like this, right? Which is a far cry from, you know &mdash;I remember when I was a kid, there was no such thing as computers, right, we had an Atari, we maybe had Omega or something like that &mdash;and what was also interesting in 1998 is actually that&#8217;s the first job I ever had in Web and it just happened to be for &mdash;doing web design and development &mdash;for a Mobile company in Seattle, Washington and that was what Mobile looked like, that was the Mobile web, that was the most advanced phone in 1998. It was black and white, and many of you might have had this phone, or seen this phone? But this was one of the early WAP browser phones, and so I&#8217;ve just kind of grew up, I came up through the web industry working, doing websites and working on these applications but at the same time, every application we built also had to work on this phone. So that gave me this kind of interesting perspective on technology and what not and that all happened in 1998. So in 2000, of course, the Millennium occurs and this was kind of a big milestone for everyone, and so we&#8217;re all kind of asking ourselves, well, you know what happened tomorrow and where&#8217;s the flying cars? Right? Because in 2001 we were kind of expecting, to some degree, that this was going to be the future and this was going to be the future of computing, right?</p>

<p>But then something, you know, pretty awful happened, of course, and that kind of changed it and that made us kind of reassess some of our needs, which I think is interesting but&hellip; I think one of the most fascinating things that occurs that I was Googling this and Googling this and trying to find more references of this, but I talked to&hellip; I actually worked at a children&#8217;s hospital right around 2002 or so, and one of the things that occurs after any sort of sociological crisis is this phenomenon called End of the World Babies. Now basically any time that people&#8217;s needs or their safety is threatened, they start getting busy and they start having lots of kids, they&#8217;re thankful for being alive. And so basically we had this baby boom that is&hellip; it&#8217;s hard to kind of judge where we&#8217;re at with it, but many early estimates expect that the post 9/11 babies are going to outnumber the Baby Boomers, which so far is the largest generation that we&#8217;ve had. And so, which is great because hopefully one of them will invent the flying car.</p>

<p>So I was actually one of them, in 2003 I had my daughter &mdash;BJ&#8217;s her nickname &mdash;and so we had our daughter, she kind of came right after that and so obviously as, once you become a parent, you start to have a slightly different perspective of things, where you start planning for their future instead of your future. And in 2006 it was kind of interesting, this was the year I started my first agency. This was kind of the picture of the Web, right, we had kind of moved into this Web (unintelligible 11.10) realm and we&#8217;ve had all these different services that are all kind of searching for this need. And it was also interesting, that same year that Duke University did a study and they found that the number of friends that we talk to about important issues had dropped from three to two. But more alarmingly, twenty five per cent stated they had no close friends at all. So the Web, now about a decade old or so, a little bit less than that &mdash;the Web was supposed to bring us together but somehow it pulled us apart.</p>

<p>So what happened there, we have this age of prosperity, we have all these exciting things that are happening and it just wasn&#8217;t materialising and helping us as people. And so I think also during that year, this is the theme of&hellip; and the Mobile community was talking about this concept of Mobile 290, which is the equivalent of Web 290, was&hellip; let&#8217;s just say that the next evolution of Mobile is really about the Web. And so we could do some interesting things, the RAZR at the time was a very popular device, and actually one of the best selling Mobile devices ever at this point, and so you could do these interesting progressive enhancement things just with HTML, CSS, and you could have a website and a mobile site pretty easily. You weren&#8217;t really addressing the context, but it was a nice trick. And in 2006 this was the device of the future, which I know was very popular over here, it didn&#8217;t quite&hellip; we got it in 2007&hellip; didn&#8217;t really quite take off. But again, I like to look at my daughter and look at this perspective and think about it, and this picture always comes to mind &mdash;this was when I was at a speakers&#8217; dinner in Australia &mdash;that&#8217;s my first Gen icon sitting on a business card that&#8217;s cut just so to create an easel, because I carry shows on that for her and then,whenever she&#8217;s bored when she&#8217;s traveling with us especially, I can just put on a show for her and we can talk a little shop and&hellip; but it&#8217;s so fascinating that she has just immediately adapted to this technology. The now for her, everything is touch, right? If she sees some sort of interface, she just immediately wants to touch it, to interact with it, which is such a fascinating transformation from my perspective and what I consider to be the devices of the future.</p>

<p> And so anyway, so this got me thinking about this concept which I later found out is basically&hellip; BJ is part of Generation Z or Zed&hellip; and basically they&#8217;re born in the middle of the digital age, right, so the technology is just infused into their lives at a rate that we could never imagine. And so the iPhone is to them as the Macintosh was to us, which I think is just such a fascinating concept. And then you add to that, you already have Generation Y, this is that generation that was born in 1991 or so, and that came after our generation and so between 1980/1990, solve problems using their social network, the real social network, they&#8217;re group thinkers, and they make buying purchases collectively, not individually, and they use mobile technology to stay informed. Ninety seven per cent of them own a computer, seventy six per cent of them use instant messaging, sixty nine per cent use Facebook, fifty six per cent own an iPod, and ninety four per cent of them own a mobile phone. These are the teenagers of today, the tweens is what we used to call them, you could call them the Millennias.</p>

<p> So I started thinking, well what if you have these two generation&hellip; this division&hellip; you have this generation that was born after 1991 &mdash;two generations &mdash;who were born after 1991. The Generation Y grew up with the Internet, Generation Z grew up with mobile, with basically the mobile Web, and so what if you combine those, what does that start to look like? And so you start to see some really interesting things happen, starting this year, that over the next five years, they predominantly outnumber us. This is one of the fastest shifts in power that we&#8217;ve ever seen in generations.  So in less than five years the mobile generation, as I call it, Y and Z, will have more buying power than all other demographics combined and that includes the Baby Boomers, that includes Gen X.</p>

<p>And so then in 2007, this device came out and I think this is&hellip; especially when I come over here, I think people under-estimate the importance this device had. Having been in mobile since, well, almost ten years at this point, this was the device we always talked about and to put it into perspective, the iPhone is the fastest consumer electronics ramp-up since the DVD player, right? So that was the previous record holder. This has become, in about eighteen months, it become the best selling mobile device ever, which supplanted the RAZR, which took them about four years to reach that goal. And they did it in a very short amount of time. And then also what&#8217;s interesting is that Generation Y that we talked about that grew up with the teardrop/gumdrop computer, is actually a little bit less powerful than the First Generation iPhone. So in just nine years we went from that being computers to this being computers. So it&#8217;s almost as if the &mdash;you know when my daughter grows up, that this is going to be her perception of computers, which I think again is all very fascinating. What can we learn from this? Again, I don&#8217;t have to actually have any solid evidence of that. But also, in just two years&#8217; time, we&#8217;ve also seen that the iPhone platform is the fourth largest platform in the world. So now it&#8217;s still rivaling Linux &mdash;iPhone and iPod touch haven&#8217;t combined, haven&#8217;t quite reached the power of Linux &mdash;but mostly likely, by the end of this year, these numbers will actually be higher than Linux, so that would make the iPhone platform the third most utilised platform in the world according to this Internet applications.</p>

<p>Now if you remove all the desktop computers from that chart, you&#8217;d actually start to see&hellip; and you put all the different mobile data into a pie chart, you&#8217;d see that iPhone is about two-thirds of all&hellip; the devices accounting for two-thirds of all Web traffic, mostly on the Web, and then what&#8217;s also interesting is if you add iPhone, Android, Symbian and Palm and actually possibly even Blackberry, now that they just made an acquisition last week &mdash;you actually start to see those are all Webkit. Those are all devices that use Webkit as their browsing technology. So you&#8217;re seeing, you know, a good seventy to eighty per cent of the top platforms that are accessing the Web are all actually using the same browser platform, which we can learn a lot from.</p>

<p>So in 2008, I was asked to do a technical review of this book, &#8216;Universal Design&#8217; by my former co-founder, Matt May and Wendy Chisholm who both wrote the &#8216;WIC aspect&#8217; when they were at the W3C, and so I was reading through the book and they were talking about the universal designers &mdash;started with accessibility, but then they also wanted to talk about rich Internet applications and whatnot &mdash;and so we started thinking, Matt used to always caution me that accessibility and SEO aren&#8217;t the same thing. And he always said, &#8216;There&#8217;s a clear line there.&#8217; But then, as we were having this discussion with them, we said ok, we have accessibility, we have SEO, we have IRIA and then now we also have social media, and you know, aren&#8217;t these all kind of the same thing? And if we add mobile to the mix, aren&#8217;t these all kind of the same thing, aren&#8217;t we just&hellip; we&#8217;ve separated our presentation from our mark-ups, we have all this content that&#8217;s all kind of well formed, and that&#8217;s sitting out there, and now we&#8217;re just kind of starting to adapt it from multiple contexts. So aren&#8217;t we talking&hellip; we&#8217;re talking about universal design? Aren&#8217;t we talking about that same thing? And so the question they started to ask is XHML, HTML5, CSS, CSS3, Javascript, XML, APIs &mdash;is this the new universal language? Right? For how we&#8217;re going to describe all the interfaces of tomorrow? And so&hellip; and what about contexts?</p>

<p>So I started to think about this more and more, and started to realise that we actually are already designing the interfaces of tomorrow, today. We may not be manifesting them in as many ways as we can imagine right now, but just by doing things the correct way with the W3C so it&#8217;s correct correct, what your, you know, favourite author might say is correct. But doing things the right way, we&#8217;re actually making all of our content available for all the devices of the future. So let&#8217;s talk about those. Let&#8217;s bring it up to today.</p>

<p>So we have the App Store, which has been also a monumental success for Apple, and has definitely been a great asset for the iPhone platform, and so&hellip; but it&#8217;s also&hellip; it falls into the same models as what we&#8217;ve seen in mobile for a decade prior. It&#8217;s still this controlled ecosystem, that&#8217;s controlled by few, that requires certification, requires submission and it requires that we abide by the rules of others, right? And that works for some of us, we can do some interesting things there, we can make money certainly. But it also starts to kind of break some of that universal language, it breaks our ability to adapt our devices for multiple contexts. So I started thinking about this &mdash;oh, the other point I wanted to make too is the other interesting thing that occurred with the Apstore is now we actually have more applications written for the Mac OS platform which runs on the iPhone, basically written in Coco &mdash;we have more applications for this little device than we did for the Macintosh user. The Mac user, for twelve/thirteen years or so, and it&#8217;s amazing how many applications we&#8217;ve seen in such a short period of time for this little device that are actually written in the same language as what I was begging &mdash;and still beg &mdash;Adobe to write, like a neater version of Photoshop.</p>

<p>So you have all these people that are actually creating these applications, and designing them for the mobile context, and so how is this&hellip; how is mobile starting to change design? And then an interesting thing happened earlier this year, that we had Tweetie, which is one of my favourite Twitter applications for the iPhone which is on the left, and they actually, the makers of Tweetie, created a desktop application for Mac that is kind of based off of the iPhone application. And that&#8217;s actually one of the first times that I&#8217;ve actually ever seen an application made for the mobile context first and then designed for the desktop context later. And so I started thinking to myself, is this the future of design? Are we going to start designing for the mobile context first, which is more constrained, which makes us have to focus on the user&#8217;s needs, on the user&#8217;s goals, much more than we do on the Web? Yesterday we were talking a lot at my workshop, we were mentioning how in the Web, I feel that we&#8217;ve gotten a little bit lazy about how we&#8217;re approaching design. That as screens have got bigger, we&#8217;ve said, &#8216;Oh, well we&#8217;ve got to fill this space,&#8217; or actually it&#8217;s usually not us, it&#8217;s usually our clients. Or our bosses. Saying, &#8216;Well, I&#8217;ve got this big screen and we&#8217;ve got to fill all the space.&#8217; It&#8217;s like, &#8216;I&#8217;ve got, you know, 1200 pixels to fill, right?&#8217; And so we keep filling that and filling that, and what cost are we paying for that, right? We&#8217;re deluding the message that we&#8217;re trying to create and we&#8217;re giving the user way more options, whereas in mobile we don&#8217;t have that luxury, we still have to think about the user first.</p>

<p>And so this is one of the things that I think is so fascinating about mobile design, is you really have to understand those principles of user centered design in order to make a successful design. So the point here is, are we designing for the medium or are we designing for the context? Right, are we designing for the Web medium when we go about solving our design problems? Are we thinking about the Web medium, about that screen size? We kind of moved away, we can now kind of say those days of when we&hellip; of the crossover between print and Web are kind of gone now. But now we&#8217;re starting to see this crossover between Web and the mobile. Are these two different mediums?  Are they the same medium? I don&#8217;t know. There&#8217;s lots of debate about that. What I can tell you is that mobile design is about context and this is a really big word, because I use it constantly, probably a little bit too much. It is the circumstances that form the setting of an event or an idea, right? This transforms how we understand information and in the Web, the context is pretty simple, you can assume the user&#8217;s behind a desk, you can assume they have a mouse, they can assume they can read the screen, you have all sorts of assumptions about the user and you design for those assumptions. But when you add context to the mix, especially mobile context, then suddenly we can&#8217;t make those assumptions. We don&#8217;t know if the user&#8217;s indoors or outdoors, right? So if they&#8217;re indoors, then we can assume a certain light level so we can use a different colour palette. But if they&#8217;re outdoors, then they could be in bright sunlight which means we&#8217;d have to use a completely different colour palette.</p>

<p>But to, I think, to illustrate something that probably everyone in this room can understand is, we&#8217;re dealing with context and we&#8217;re actually publishing our context every day through this application, right? So we&#8217;re&hellip; and people around the world, especially I think the Iran elections are so interesting, that we were able to understand ideas and things as they happen real time just by using this one service. And we&#8217;re doing that every day, we&#8217;re publishing our context, we&#8217;re telling our friends. I know a lot of people think it might be useless to say, &#8216;Well, I&#8217;m, you know, having dinner,&#8217; or whatever, but you&#8217;re trying to inform people where I&#8217;m at, what I&#8217;m doing, and then when that&#8217;s interesting to other people, then they can understand your context a little bit and maybe understand where you&#8217;re coming from in a very rudimentary way.</p>

<p>But we also see it in contexts in these real time events like the Iran election, where this event was taken &mdash;the photo that you saw in the news &mdash;was taken with a mobile device. So we&#8217;re able&hellip; and it was published through Twitter as it happened, so we were immediately able to bond with the events that occur almost in real time through these mobile devices and understanding contexts. And we&#8217;re using it all the time where we&#8217;re using geo-location features to be able to find where we want to go, to find a restaurant, find our friends, find all this information that is out there and it&#8217;s coming to us. And I use this one, in the book, I use this, where I got lost in Berlin because I just didn&#8217;t speak German. And I wanted&hellip; I was just walking around and I wanted to kind of take in Berlin and so I was able to use my mobile device to actually translate the things I was standing right in front of and understand the contextual importance it was to people many years ago, like the historical significance.</p>

<p>Or we can actually use augmented reality which is another popular buzz-term, but we can overlay the information found on the Web using our mobile devices &mdash;this application is called Wikitude, where you just aim your camera, a live view of your camera, at some sort of space and then it will pull down information from Wikipedia and present it on screen and as you pan around, it&#8217;ll update that display and this works on Android devices. And so now, when you&#8217;re a tourist, now you won&#8217;t look at any monument the same way. Unfortunately, I didn&#8217;t have this when I was in Berlin, otherwise I would have been the worst tourist, walking around like this! So this era of the single context, so that just thinking about the Web, is over. And it&#8217;s not just about mobile devices, it&#8217;s also about people with disabilities, it&#8217;s about machines being able to read our content. As well as new devices that are coming up, this is the opera browser that is found on the Wii, which is an incredibly the best-selling game console right now. And you also have the web browser that&#8217;s in the PS3, which is ironically enough made by a mobile browser maker! Or you actually have Web widgets and Web platform actually making its way onto Panasonic TVs. In fact as I was flying over here, I was reading the most recent copy of Wired and they were reviewing, like, five or six different TVs and they were criticising some of the TVs for not having net capability, not being able to do net flick streaming, not being able to stream content directly to the TV.</p>

<p>So this is this world that BJ is going to be growing up with, right? It&#8217;s only starting for us and as a six year old now, she is going to be adapting with these different experiences in ways we can&#8217;t even imagine yet. And so another thing that&#8217;s fascinating and I learned about this way before I actually started out in the Web, is Neural Linguistic Programming which is kind of the different contexts in which we learn information and the different senses that we use in order to absorb and attain information. And kind of like Maslow&#8217;s hierarchy of needs, I kind of found that these recurring principles that occur in any sort of user experience, is that any time &mdash;even me here talking to you today &mdash;is that my goal as a speaker is to tap into the three primary different ways that you&#8217;re going to assess information. There&#8217;s auditory, which is twenty per cent of the room; there&#8217;s visual which is you&#8217;re going to respond to the visuals of the slides which is thirty five per cent of the room; and then there&#8217;s kinaesthetic, which hopefully you&#8217;re going to retain something and then you&#8217;re actually going to do it. And that&#8217;s how you&#8217;re going to retain whatever I tell you, or whatever you learn here today.</p>

<p>And so one of the diagrams that I use to kind of illustrate this from the opportunities in mobile is, so what if you put the user in the centre as we always should and you surround that by the three different ways we assess and retain information, and then we can actually start to put a circle around them of all the different medias that are available to them as they just go about their lives. Mobile devices actually only being one of them &mdash;but they see print ads, they see billboards, they see spots on TV or radio, or doesn&#8217;t matter, and then we can actually then connect that with a variety of different mobile technologies &mdash;SMS, the mobile Web, QR codes &mdash;and then we can actually help them achieve their goals, which I know is a little bit hard to read but we can help them achieve their goals, to be able to buy something, to notify their friends, to get some place on time.</p>

<p>And so what we have to do is, we have to start thinking of design not as the singular Web based interface, web applications or the technology &mdash;we have to think of it as a multi-faceted experience that we&#8217;re going to surround the user with, it has so many different choices, especially my daughter. She&#8217;s going to grow up with so many different options in life that we have to think about, ok, we have services like Twitter &mdash;well Twitter isn&#8217;t really about&hellip; the product isn&#8217;t a website, the product is this API that we&#8217;re able to tap into with lots of different clients, right? So there&#8217;s the user has choice and it can be there when they need to be there, right? So these solutions can become kind of these invisible services that we have round the world.</p>

<p>So the question, again, the theme of the talk, is &mdash;what&#8217;s next? And I like to think it&#8217;s anything, it&#8217;s everything, it&#8217;s such an exciting time, the entire world is in front of us, right? We&#8217;re here today to kind of talk about some of tomorrow&#8217;s innovations and I believe that they come from the investments that are being made into mobile today. And that we&#8217;re seeing some very interesting things occur in the iPhone space and the Android space, Palm just completely reinvented itself, basically creating an entire mobile platform based off of a webkit, and so their entire application platform has just &mdash;HTML, CSS and some Javascript &mdash;but it&#8217;s not going to happen because of iPhone, Android, operate phones, operators &mdash;it&#8217;s going to be happening because of people, because people need some of these solutions, right? The mobile technology, by its very nature, is designed to facilitate interaction between people. It&#8217;s a communication device, right?</p>

<p>So I keep coming back to Jessie&#8217;s diagram, that talks about information as a hypertext system, information as a software interface and I keep coming back to this and wondering &mdash;is this still accurate? Do we have more layers that we&#8217;re dealing with? Or can we apply the same layers that we&#8217;ve been using for Web interfaces, for software interfaces, and can we apply those to the mobile context, or any context in this user centered new era that we live in? And I kind of think yes, I think that we can because a lot of the standards and a lot of the technology of where it&#8217;s headed is moving in this realm of progressive enhancement. That we can provide multiple experiences that basically degrade, and we can start by designing the best possible experience on the best possible platform for that user in the assumed context they may be in. But then we can also &mdash;again by adopting standards, by adopting kind of the same principles that I&#8217;m sure all of you here already know &mdash;that we can actually apply those principles and we can make experiences that work, not only for tomorrow&#8217;s devices but for the devices of today, and one of them, you know, being Web browsers.</p>

<p>So it&#8217;s not just about mobile. Now are we getting any closer to flying cars? Probably not. Am I going to see flying cars in my lifetime? Probably not. I&#8217;ve kind of come to this realisation. I&#8217;m reading this very fascinating book, it&#8217;s called &#8216;The Physics of the Impossible&#8217; that talks about that we actually don&#8217;t quite understand how that anti-gravity is really just a matter of creating a room temperature semi-conductor, and the closest we&#8217;ve gotten to that, we don&#8217;t actually understand the physics of what makes it possible. We&#8217;re like a couple&hellip; I think, ten or twenty degrees below Kelvin right now, so we&#8217;re pretty close to room temperature but we don&#8217;t actually know why. So &mdash;but, you know, is that something we&#8217;re going to see in our lifetime? My lifetime? Probably not. But then, you know, I start to think to myself, is that the innovation of tomorrow that I&#8217;ve been waiting for ever since I was a kid? Or is it something more like this? Is it this thing that we can bring the world closer together where we have two-thirds of the population of the planet has these mobiles devices? And we&#8217;re actually the ones that are the gatekeepers of the information age, we&#8217;re the publishers, we have the keys to the kingdom. We&#8217;re the ones that are going to put all this information out there for them to assess and to be able to communicate and be able to talk and collaborate.</p>

<p>And so we have this new innovation that I think is going to define tomorrow, and it&#8217;s bigger, it has a more lasting impact than being able to get from, you know, Point A to Point B faster or over the air which, even though that would be very exciting&hellip;. but then mobile devices are portable, personal and ubiquitously connected, always on. And so we can contact people, it allows us to not only to communicate with them in real time, but also collaborate and be able to share information experiences in ways we never could do before. And so I believe that we&#8217;re already actually in the midst of this new industrial revolution and it&#8217;s not this Web 290, it&#8217;s not anything so trite, it&#8217;s something that no-one&#8217;s really quite been able to put their arms around yet. We haven&#8217;t quite been able to define what this is. But in technology, I mean, it&#8217;s hard to think, it&#8217;s like ok, well ten years ago, you know, the iPhone was the iMac in ten years from now, but what are these stepping stones that we&#8217;re going to create that actually lasts for the next hundred years? What&#8217;s going to be that industrial revolution that creates the amount of innovation? And are we the best generation to actually be able to solve that? Because we&#8217;re the optimists, we grew up with this technology, we understand the days before and we understand the days ahead. And so we&#8217;re right at that tipping point, and we&#8217;re also &mdash;I can tell by many of you, just by looking at the general age in the room &mdash;is&hellip; I think many of you are independent thinkers, you&#8217;re free thinkers, which are some of the traits that some of the younger generations don&#8217;t quite have yet. And so I believe that mobile is actually where the conversation begins.</p>

<p>So, how do you design for tomorrow? Well, I consider myself a bit of a Taoist, try to as good as I can and there&#8217;s a Taoist saying &mdash;&#8216;The good teacher teaches the student that they already know the answer,&#8217; right? And you already know this, or you know most of it. I have no doubt in my mind that this is something you feel pretty comfortable with. And that this is becoming universal language for everything, which again puts you guys in the driver&#8217;s seat to be able to create these experiences of the future. And so I believe it starts here with you today, and that you&#8217;re already doing it and you just need to keep doing it, and you need to keep selling it, you need to have that passion and look towards the future and say, &#8216;This world that we live in that maybe our clients, maybe our bosses are still kind of living in that decade past, we&#8217;re living in the decade ahead.&#8217; And so with that, I thank you. My book is available outside, it&#8217;ll actually be available in bookstores next week. None these topics are in the book, but thank you very much!</p>
</blockquote>

</div>

<!-- FOOTER -->
<?php include($dr . "footer.inc.php"); ?>